<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="zqy-PC" name="com.ctsi.test.MessageCenter" tests="1" failures="0" timestamp="20 Aug 2013 02:27:08 GMT" time="3.017" errors="1">
  <testcase name="verifyHomepageTitle" time="3.017" classname="com.ctsi.test.MessageCenter">
    <error type="java.lang.AssertionError" message="[验证失败] 验证外勤助手主页面标题是否正确 期望值:&lt;中国电信外勤助手&gt; 实际值:&lt;&gt;">
      <![CDATA[java.lang.AssertionError: [验证失败] 验证外勤助手主页面标题是否正确 期望值:<中国电信外勤助手> 实际值:<>
	at com.ctsi.tools.BaseCase.fail(Unknown Source)
	at com.ctsi.tools.BaseCase.failNotEquals(Unknown Source)
	at com.ctsi.tools.BaseCase.assertEquals(Unknown Source)
	at com.ctsi.tools.BaseCase.assertEquals(Unknown Source)
	at com.ctsi.test.MessageCenter.verifyHomepageTitle(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.TestNG.privateMain(TestNG.java:1338)
	at org.testng.TestNG.main(TestNG.java:1307)
]]>
    </error>
  </testcase> <!-- verifyHomepageTitle -->
</testsuite> <!-- com.ctsi.test.MessageCenter -->
